keys:
  - &primary age1mzq5jd3xtdyldktqcaxtn2hde9k7a32d35f052nwf2ctuz2l5srsprjuen

creation_rules:
  - path_regex: shared/secrets\.yaml$
    key_groups:
      - age:
        - *primary
  - path_regex: maas/secrets\.yaml$
    key_groups:
      - age:
        - *primary
<<<<<<< HEAD
=======
  - path_regex: deck00/secrets\.yaml$
    key_groups:
      - age:
        - *primary
>>>>>>> e45c6a6 (Add shared secrets and restructure for common secrets module)
  - path_regex: needl/secrets\.yaml$
    key_groups:
      - age:
        - *primary